name: Go Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  windows:
    runs-on: ubuntu-latest
    env:
      GOOS: windows
      GOARCH: amd64
      CGO_ENABLED: 1
      CC: x86_64-w64-mingw32-gcc-win32
      PKG_CONFIG_PATH: /usr/x86_64-w64-mingw32/pkgconfig
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install MinGW-w64
        run: sudo apt-get install --yes gcc-mingw-w64-x86-64-win32
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v .